{{- range .Values.namespaces }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ . | quote }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
