{{- $policyName := "dont-automount-service-account-token" -}}

{{- if .Values.dontAutomountServiceAccountToken.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $policyName }}
  annotations:
    "policies.kyverno.io/title": "Don't Automount the Service Account Token"
    "policies.kyverno.io/description": |
      The service account token allows contacting the kubernetes API. Without proper authorization set for the service account, at the bare minimum, sensitive information about the cluster might be accessible if the container is compromised. At most, an intruder can wreak havoc in the whole cluster. Since most applications do not require access to the kubernetes API, it's better to disable this setting.
spec:
  validationFailureAction: {{ .Values.validationFailureAction }}
  rules:
  - name: {{ $policyName }}
    match:
      any:
        - resources:
            kinds:
            - Pod
            namespaces: {{- toYaml .Values.namespaces | nindent 14 }}
    validate:
      message: "`automountServiceAccountToken` should be disabled unless the pod requires access to the kubernetes API."
      pattern:
        metadata:
          <(annotations):
            "X(kyverno.haff.xyz/ignore-{{ $policyName }})": "?*"
        spec:
          automountServiceAccountToken: false
{{- end -}}
