{{-  $policyName := "require-requests-and-limits" -}}

{{- if .Values.requireRequestsAndLimits }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $policyName }}
  annotations:
    "policies.kyverno.io/title": "Require Requests and Limits"
    "policies.kyverno.io/description": |
      Providing resource requests for a container helps the scheduler better decide what node is appropriate to run the pod. Without resource limits, containers can grow unbounded, starve other pods and allow denial of service attacks. In general, providing resource requests and limits makes container resource usage more predictable.
spec:
  validationFailureAction: {{ .Values.validationFailureAction }}
  rules:
    - name: {{ $policyName }}
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces: {{- toYaml .Values.namespaces | nindent 14 }}
      validate:
        message: You should provide resource requests and limits for your containers.
        pattern:
          metadata:
            <(annotations):
              "X(kyverno.haff.xyz/ignore-{{ $policyName }})": "?*"
          spec:
            containers:
              - resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
                  limits:
                    memory: "?*"
                    cpu: "?*"
            =(initContainers):
              - resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
                  limits:
                    memory: "?*"
                    cpu: "?*"
            =(ephemeralContainers):
              - resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
                  limits:
                    memory: "?*"
                    cpu: "?*"
{{- end -}}
